obj=open("E:/suma.txt","w")
c=obj.write("hello thammudu")
print(c)
obj.close()
#obj=open("E:/priya.txt","r")
obj=open("E:/priya.txt","w")
obj.write("rinky you are so cute and sweet")
#c=obj.write()
#print(c)
obj=open("E:/priya.txt","a")
obj.write("rinky is so good gril")
obj.close()